### ISSUE TITLE
Make fails on protoc-gen-go (incorrect URL)

### ISSUE THREAD

**Issue by hesa** [QMSTR/qmstr#436]
I followed the instructions at https://qmstr.org/documentation/introduction/installation/ and am getting stuck here:

$ make install_qmstr_client
/usr/bin/go install github.com/golang/protobuf/protoc-gen-go
can't load package: package github.com/golang/protobuf/protoc-gen-go: cannot find package "github.com/golang/protobuf/protoc-gen-go" in any of:
	/usr/lib/go-1.10/src/github.com/golang/protobuf/protoc-gen-go (from $GOROOT)
	/home/hesa/gopath/src/github.com/golang/protobuf/protoc-gen-go (from $GOPATH)
Makefile:78: recipe for target '/home/hesa/gopath/bin/protoc-gen-go' failed
make: *** [/home/hesa/gopath/bin/protoc-gen-go] Error 1

Path to protoc-gen-go, as specified in qmstr's top level Makefile, does not exist.:
$(PROTOC_GEN_GO):
        $(GO) install github.com/golang/protobuf/protoc-gen-go

Doing HEAD on the URL gives:
$ HEAD github.com/golang/protobuf/protoc-gen-go
404 Not Found
Cache-Control: no-cache
Connection: close
... etc etc etc

-------
My system:
Ubuntu 18.04.03 LTS (DELL XPS 13, Intel® Core™ i7-8565U CPU @ 1.80GHz × 8 )

**Comment by hesa** [comment]
Read the https://github.com/golang/protobuf installation guide and tried:

$ go get -u github.com/golang/protobuf/protoc-gen-go

Seems to work now. But I figure it is worth looking into :)

**Comment by sebastian-su** [comment]
I can reproduce the issue, we will look into it. Thanks.

**Comment by sebastian-su** [comment]
on my test setup the problem is the missing gobin path which is not mentioned in our readme. If thats missing the protobuf-gen-go is installed correctly but not found in the path. We will update that in the documentation. I created a simple build environment dockerfile here: https://github.com/endocode/qmstr_buildenv/blob/master/Dockerfile . With these steps (except the jenkins specifc parts) you should be able to set up the build env correctly.
